### ISSUE TITLE
Cross site scripting vulnerability

### ISSUE THREAD

**Issue by Michael-Brooks** [w3c/webmention#115]
Hello,

I installed this plugin and was recently notified of a potential security hole on my website. When a user went to [https://michaelbrooks.co.uk/restarting-my-podcast/?replytocom=</SCript><svG/onLoad=prompt(9)>](https://michaelbrooks.co.uk/restarting-my-podcast/?replytocom=%3c/SCript%3e%3csvG/onLoad=prompt(9)%3e) it would display a prompt where the user could inject JS.

![image](https://user-images.githubusercontent.com/3197231/223767125-5587db5c-ed0c-46a7-a2e5-dea7e94fb6b2.png)

I spoke to WordPress.com helpdesk, who identified the issue was coming from this plugin. Here is the bounty that the hacker generated for my blog https://www.openbugbounty.org/reports/3211320/

**Comment by aaronpk** [comment]
Hi Michael, this repository is for the Webmention specification, not any particular plugin. You are probably looking for the WordPress Webmention plugin here: https://github.com/pfefferle/wordpress-webmention
