### ISSUE TITLE
Definition of 'link'

### ISSUE THREAD

**Issue by rhiaro** [w3c/webmention#43]
Abstract:

>  Webmention is a simple way to notify any URL when you link to it on your site. From the receiver's perspective, it's a way to request notifications when other sites link to it. 

Intro:

> At a basic level, a Webmention is a notification that one URL links to another.

'link' is debatable given that a plain text file with a URL in it is a valid webmention source. Something like:

"Webmention is a simple way to notify any URL that it appears on your site. From the receiver's perspective, it's a way to request notifications when others sites refer to it."

"At a basic level, a Webmention is a notification that one URL appears at another."

**Comment by kevinmarks** [comment]
On 26 May 2016 8:40 am, "Amy Guy" <notifications@github.com> wrote:
>
> Abstract:
>>
>> Webmention is a simple way to notify any URL when you link to it on your
site. From the receiver's perspective, it's a way to request notifications
when other sites link to it.
>
> Intro:
>>
>> At a basic level, a Webmention is a notification that one URL links to
another.
>
> 'link' is debatable given that a plain text file with a URL in it is a
valid webmention source.

The point is the intent to link to the target though. The webmention
receiver has discretion on how to interpret the sender document, and could
broaden parsing. Base url handling already means that a pure text match
will miss some mentions.

Something like:
>
> "Webmention is a simple way to notify any URL that it appears on your
site. From the receiver's perspective, it's a way to request notifications
when others sites refer to it."
>
> "At a basic level, a Webmention is a notification that one URL appears at
another."
>

This language adds vagueness without mandating anything about
implementation.

**Comment by rhiaro** [comment]
This is just editorial, so it doesn't 'mandate anything about implementation' anyway. I thought the generality (or 'vagueness') is preferable to a specificity that isn't technically correct.

An alternative would be to say 'intend to link' or explain this broader definition of 'link' that's being used.

> The webmention receiver has discretion on how to interpret the sender document, and could broaden parsing

I thought this was only when the content type is anything beyond HTML5, JSON or plain text? Those three are the ones explicitly mentioned in the spec, and only the HTML5 is technically a 'link' in web architecture terms.

**Comment by aaronpk** [comment]
I've changed the text from "links to" to "mentions", since that covers both linking in an HTML document and referencing in plain text.
