### ISSUE TITLE
section 3.1.2 charset

### ISSUE THREAD

**Issue by r12a** [w3c/webmention#56]
[raised by Addison Phillips, discussed in i18n telecon]

https://www.w3.org/TR/webmention/#sender-notifies-receiver

Section 3.1.2 describes the submission of the `source` and `target` URLs in the `x-www-form-urlencoded` format. There is no mention of character encoding, which normally is an important concern for this format. However, since the strings in question are URLs, they are presumably already "URL encoded" using the character encoding recognized by the host server. I'm raising this issue to point out that the charset issue works in this case. However, if fields were added to the payload in a future revision, the charset might become important.

**Comment by aaronpk** [comment]
Thanks for pointing this out. There is currently no plan to include non-URL values in parameters of the Webmention payload, so like you said, all values are already URL encoded. Since you indicated that this works right now, I'm going to go ahead and close this issue.
