### ISSUE TITLE
section 3.2: no character encoding on response examples

### ISSUE THREAD

**Issue by r12a** [w3c/webmention#58]
[raised on behalf of Addison Phillips, discussed in i18n telecon]

https://www.w3.org/TR/webmention/#receiving-webmentions

In Section3.2 there are examples of responses. They are giving the `Content-Type` of `text-plain` with *no* charset parameter. Please include a charset=UTF-8.

Should there also be a health warning to use UTF-8?

**Comment by aaronpk** [comment]
Thanks, I've added the charset to the content type header in the examples. You can see this reflected in the current editor's draft: http://webmention.net/draft/#receiving-webmentions

**Comment by aaronpk** [comment]
Removed the examples of content-type header in the response, and un-added charset to the POST request.
