### ISSUE TITLE
Caution regarding using form encoded data

### ISSUE THREAD

**Issue by melvincarvalho** [w3c/webmention#60]
Given that webmention is strictly based on form-urlencoded data, it'd be important to caution implementers on what the W3C Recommendation for HTML5 says (see note): 

https://www.w3.org/TR/html5/forms.html#url-encoded-form-data

**Comment by akuckartz** [comment]
Drastic text but :+1:

**Comment by dissolve** [comment]
It seems pretty random to just copy-paste a commentary about form-encoding.  This would really be at the level of anyone writing a form-encoding processing anyway, which is a different level than webmention implementors are likely to care about (I don't really know of any realistically usable stack that doesn't already have built-in form-encoding processing already).

If you wanted that warning to really make sense, you would have to put the entire section on how to actually process form-encoded data, which can be simply accomplished by referencing the relevant section of the HTML spec.

**Comment by aaronpk** [comment]
The spec already has a normative reference to HTML5 where that paragraph is. Since the paragraph is talking about the implementation of form-encoding, it only makes sense in the context of the encoding algorithm as detailed in HTML5. 

That level of detail is only relevant to someone implementing a form-encoding or decoding function, the vast majority of which are already built into every HTTP library and web framework that exists. Implementers of Webmention typically do not need to worry about the mechanism of form-encoding itself, similar to how implementers of any spec that uses JSON do not need to concern themselves with JSON encoding and parsing.

**Comment by aaronpk** [comment]
We discussed this in the call today, and came to the agreement that it's not necessary to include editorial text about encoding and parsing form-urlencoded data. Similar to how you will not find text describing JSON serialization and parsing in specs that use JSON, there is no need to describe that lower level in Webmention. Closing as agreed: https://www.w3.org/wiki/Socialwg/2016-08-02-minutes#issue-60

**Comment by melvincarvalho** [comment]
@aaronpk thanks for the update.  Unfortunately I could not make the call, and sent my regrets via IRC and the wiki, prior to the call, as I had a guess.  I find it unusual that this was voted on so quickly without waiting for input from the commenter.  Isnt it normal procedure to wait a week in such instances?

However as @aaronpk seconded this and was present during the vote, that I think was good.

So, in the case of JSON there are no notes that I know of showing that JSON parsing is problematic.  The W3C spec seems to indicate via a note that form encoded url parsing is perhaps problematic.  This is not about how to parse form encoded data, as I think libraries do that.  The question here is to what extent the text of the HTML5 spec describes the parsing as problematic.  

For example the source and target variables.  Can they contain non ascii characters, can they contain unicode, how should it be encoded etc.  In JSON I am unaware of any issues here.  With form encoded data there appear to be warnings.  Is there any evidence that this has been looked at?  If it has, that's fine, but it's not clear from the text that the warnings in the HTML spec have worked through.

**Comment by melvincarvalho** [comment]
As a point of process, I only found out by chance and quite late, that this item was added to the agenda.

How about when adding issues to an agenda where there is an intention to vote, to reference that agenda in the github issue?

**Comment by dissolve** [comment]
> So, in the case of JSON there are no notes that I know of showing that JSON parsing is problematic. The W3C spec seems to indicate via a note that form encoded data parsing is perhaps problematic. This is not about how to parse form encoded data, as I think libraries do that. The question here is to what extent the text of the HTML5 spec describes the parsing as problematic. 

You are kind of trying to compare apples to oranges here.  You are comparing the fact that the spec for parsing of form encoding contains a note about issues with parsing, to the fact that no note that references json's spec adds a note about parsing issues (btw, json is specified in an RFC, not anything under w3c, which I find tend to contain less notes of these type).  Were I specifying JSON, I would include such a note about how there are no comments allowed in JSON.

Indeed, the fact that every spec that references JSON does not add such commentary lends more to the arguement that it is not needed here.

**Comment by melvincarvalho** [comment]
@dissolve I hear what you're saying.  I dont think there's any issues with JSON messaging, or any edge cases that have come up.

Regarding form encoded variables, my concern is whether the text has been examined to see whether there are edge cases pertinent to the values that can go in the source and target strings.  For example are non ascii characters going to be an issue, or commas or spaces.  I believe JSON is fine with this, as is turtle.

What would be good would have been someone to look thru the text and say, "OK this isnt a problem because" or "there's an edge case around certain character sets", or must they be escaped in a certain way.  So if there's an implementation issue it can be mentioned on the spec.

Alternatively if it's an edge case that's not worth caring about, I suppose that could be fine too.  But Im slightly more caution with the argument of "thats the parsers job, and nothing to do with the payload".  It might be, but has anyone actually determined that?  It wasnt clear to me.

**Comment by aaronpk** [comment]
The point is that the HTML5 spec is *where* the form-encoding parsing and encoding algorithm is described. That's an appropriate place for a warning like that. Not in a document that just references the spec. 

In Webmention, we're talking about sending two URLs in form-encoded format. That is a very well established practice and not something that is going to lead to a lot of edge cases.

There are plenty of "problems" [people cite with JSON](https://www.google.com/?q=alternatives+to+JSON) all the time. 
* It doesn't allow comments
* It's too error prone to be easily human authored
* It is too verbose
* It doesn't support a fixed schema

That doesn't stop it from being useful in certain circumstances, despite those uses not containing this list of warnings.

**Comment by kevinmarks** [comment]
Well, there is the problem of JSON-LD throwing an exception if the JSON includes a list of lists. https://www.w3.org/TR/json-ld/#sets-and-lists 

Should we warn about that in every spec that mentions JSON-LD?

**Comment by kevinmarks** [comment]
Well, there is the problem of JSON-LD throwing an exception if the JSON
includes a list of lists. https://www.w3.org/TR/json-ld/#sets-and-lists

Should we warn about that in every spec that mentions JSON-LD?

**Comment by kevinmarks** [comment]
Given that the calls have been focused on addressing open issues in drafts
for a while, as an examination of the minutes will show, the process is
unexceptional.

**Comment by melvincarvalho** [comment]
@aaronpk I'd like to respond to your comment on the use of JSON, as it is something that came up during the Social Web XG.  

Unless I hear otherwise, Im going to assume the preferred way to do this is to open a new issue and reference this one.
