### ISSUE TITLE
Why only "410 GONE" for deleted posts?

### ISSUE THREAD

**Issue by Perlkonig** [w3c/webmention#62]
Why does the spec (and the test suite) not accept "404 NOT FOUND" as well? In my admittedly limited experience, most CMS platforms don't natively support "remembering" old URLs, thus being able to return a 410. I would think a 404 response would be just as meaningful.

**Comment by aaronpk** [comment]
There is some background on that reasoning here: http://indieweb.org/deleted-404-discussion

**Comment by Perlkonig** [comment]
Thanks for the link. It all makes sense, but it's challenging in practice. I'm writing a webmention plugin for [the Grav CMS](http://getgrav.org) and will try to build a plugin to generate 410s as well.

**Comment by Perlkonig** [comment]
For the record: https://github.com/Perlkonig/grav-plugin-graveyard
