### ISSUE TITLE
Update HTTP reference to point at RFC723*

### ISSUE THREAD

**Issue by kjetilk** [w3c/webmention#63]
Just a minor issue, RFC2616 has been superseded by an array of new specs, RFC7230 and onwards. The reference should be updated to reflect that.

**Comment by kjetilk** [comment]
The concrete reference is to [RFC7231](https://tools.ietf.org/html/rfc7231). This change does not require any other changes to the specification.

**Comment by akuckartz** [comment]
:+1:

**Comment by aaronpk** [comment]
@kjetilk thanks! I've updated the reference, please close the issue if you feel it's been resolved.

**Comment by kjetilk** [comment]
Great, thanks!
