### ISSUE TITLE
Update URL reference from RFC 3986 to WHATWG URL

### ISSUE THREAD

**Issue by aaronpk** [w3c/webmention#67]
More recent W3C specs are referencing the WHATWG URL spec. (e.g. https://www.w3.org/TR/CSP2/#normative)

While this is technically a normative change, it does not affect any existing implementations. Additionally, the WHATWG URL spec is a more precise definition of URL for the purposes of Webmention.

https://url.spec.whatwg.org/

**Comment by akuckartz** [comment]
I do not understand why this should be done.

**Comment by aaronpk** [comment]
As [discussed in the telcon](https://www.w3.org/wiki/Socialwg/2016-10-25-minutes#Webmention), the original intent of adding the reference to RFC3986 was to reference what a URL was, it was mostly a coincidence that I found 3986 before I found the more up to date WHATWG URL spec. More recent W3C specs have been using the WHATWG URL spec, so this updates the Webmention references to match, since the original intent was not specifically to reference the RFC version.

**Comment by aaronpk** [comment]
Pending approval from Ralph.

**Comment by rhiaro** [comment]
In the transition call Ralph determined we either need to add some of the disclaimer text that the [HTML5 spec](https://www.w3.org/TR/html51/references.html#normative) uses about this reference, or revert back to the original RFC reference.
