### ISSUE TITLE
likely editorial: loopback exception specifically about not sending to loopbacks

### ISSUE THREAD

**Issue by tantek** [w3c/webmention#71]
In https://www.w3.org/TR/2016/PR-webmention-20161101/#avoid-sending-webmentions-to-localhost it says:

"During the discovery step, if the sender discovers the endpoint is localhost or a loopback IP address (127.0.0.0/8), it SHOULD NOT send the Webmention."

I think this should specifically apply to not sending to webmentions to loopbacks, i.e. I suggest a (likely) editorial change to:

"During the discovery step, if the sender discovers the endpoint is localhost or a loopback IP address (127.0.0.0/8), it SHOULD NOT send the Webmention to that endpoint."

Also the implementation report says:

"[ ] The sender avoids sending a Webmention to a loopback address (SHOULD)"

which is consistent with my suggested editorial change.

**Comment by aaronpk** [comment]
Agreed, this is an editorial change clarifying the scope of the limitation of sending to the loopback address. I've made the requested change.

**Comment by aaronpk** [comment]
Closing based on @tantek's +1 above
