### ISSUE TITLE
[Non-normative] Add informative reference to Pingback, brief summary of FAQ in intro

### ISSUE THREAD

**Issue by tantek** [w3c/webmention#76]
Per @hildjj at https://groups.google.com/d/msg/mozilla.dev.platform/RPu2oIc70Ug/GuZXnR1JAwAJ

"Because there has been a lot of security work done on the prior protocols, particularly in terms of implementation detail in spam prevention.  It's also just good karma to call out the giant upon whose shoulders you are standing.  Informative links from the in the document will be nice decades from now when nobody remembers that those other protocols once existed. "

and previously in that thread:

"Pingbacks and trackbacks at least. "

We should add at least a brief informative sentence to the spec (perhaps near intro/background) noting at least Pingback, and then linking to the FAQ for more details.

https://indieweb.org/Webmention-faq#Why_webmention_instead_of_pingback

In my opinion we can omit mentioning Trackback because a) it was never secured, no real experience there, b) Pingback already superseded it 10+ years ago, and c) it's in the FAQ for anyone who looks at the Pingback predecessor

**Comment by aaronpk** [comment]
How does that look @tantek?
